Fix DATE_DIFF CAST bug in supplier_lead_times.yml
Bug: DATE_DIFF used CAST(string_date AS DATE) which fails for DD/MM/YYYY format.
BigQuery CAST expects ISO format (YYYY-MM-DD) but gets '25/01/2024'.

Error: Invalid date: '25/01/2024'

Root Cause: Lines 16 and 23 used CAST(ir.trandate AS DATE) and
CAST(po.trandate AS DATE) on STRING fields in DD/MM/YYYY format.

Fix: Changed CAST to PARSE_DATE('%d/%m/%Y', ...) to correctly parse
DD/MM/YYYY format before DATE_DIFF calculation.

Impact: Fixes lead_time_rollup pre-aggregation build failure.

This is bug #39 - incomplete DATE parsing in DATE_DIFF calculations.
File: /home/produser/cube-demo/model/cubes/supplier_lead_times.yml:16,23